// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-ac3rRXnfVKXBKDrWK13ntPLQ1mbR-A',
    appId: '1:583361751686:web:062eb260492dca27ac7f07',
    messagingSenderId: '583361751686',
    projectId: 'lets-chat-6d76e',
    authDomain: 'lets-chat-6d76e.firebaseapp.com',
    storageBucket: 'lets-chat-6d76e.firebasestorage.app',
    measurementId: 'G-0N72E2LSFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFNbAlaayjNq9XNiR4-OvUYFXMt4lqjE',
    appId: '1:583361751686:android:2394b47f3ae8338aac7f07',
    messagingSenderId: '583361751686',
    projectId: 'lets-chat-6d76e',
    storageBucket: 'lets-chat-6d76e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeS1WuTAy2U4dYMQ73ZUoWcshZqfsRgw0',
    appId: '1:583361751686:ios:0fec7f3ec03b17a5ac7f07',
    messagingSenderId: '583361751686',
    projectId: 'lets-chat-6d76e',
    storageBucket: 'lets-chat-6d76e.firebasestorage.app',
    iosClientId: '583361751686-hdchle4sdjjuhitlgq8nb3n78c632rl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );
}
